### ISSUE TITLE
Roadmap to making this repo public

### ISSUE THREAD

**Issue by willtebbutt** [willtebbutt/ConjugateComputationVI.jl#1]
- [x] API: design one that's not awful.
- [x] Documentation: readme-based docs are enough for this package.
- [x] Additional example: TemporalGPs.jl -- really long time series problem
- [x] Additional example: Stheno.jl -- because it's fun and interesting
